name: Build and Deploy

on:
  push:
    branches:
      - pulsatrix

jobs:
  build-n-push:
    runs-on: [tanzu]
    timeout-minutes: 10

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0
          token: ${{ secrets.DEPLOY_TOKEN }}

      ## Prepare new version
      - name: Bump version and push tag
        id: semanticversion
        uses: mathieudutour/github-tag-action@v6.1
        with:
          release_branches: pulsatrix
          github_token: ${{ secrets.GITHUB_TOKEN }}
          fetch_all_tags: true

      - name: Verify and print new build number
        run: |
          echo "previous tag: '${{ steps.semanticversion.outputs.previous_tag }}'"
          if echo '${{ steps.semanticversion.outputs.new_tag }}' |grep -Eq '^v[0-9]+[.][0-9]+[.][0-9]+$'; then
            echo Tag '${{ steps.semanticversion.outputs.new_tag }}', New version '${{ steps.semanticversion.outputs.new_version }}'
          else
            echo 'unexpected tag format - aborting'
            exit -1
          fi

      - name: Build and push docker image
        env:
          REGISTRY_USERID: ${{ secrets.LEVIGO_NEXUS_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.LEVIGO_NEXUS_PASSWORD }}
          REGISTRY_URL: ${{ secrets.LEVIGO_NEXUS_REGISTRY_RELEASES }}
          IMAGE_NAME: "${{ secrets.LEVIGO_NEXUS_REGISTRY_RELEASES }}/pulsatrix/spilo:${{ steps.semanticversion.outputs.new_version }}"
        run: |
          cd postgres-appliance
          docker login ${REGISTRY_URL} --username ${REGISTRY_USERID} --password ${REGISTRY_PASSWORD}
          docker build \
            -t ${IMAGE_NAME} \
            --build-arg TIMESCALEDB_APACHE_ONLY=false \
            .
          docker push ${IMAGE_NAME}

      ## Notify MM
      - name: Notify MM about new release
        uses: hennejg/slack-build-notifier@v1.1
        with:
          username: GitHub
          icon_emoji: octocat
          channel: "pulsatrix-ci"
          text: Built new Spilo image `${{ steps.semanticversion.outputs.new_version }}` of *${{ github.repository }}*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.MATTERMOST_WEBHOOK_URL }}
        if: always()
